[package]
name = "uio-rs"
version = "0.1.0"
edition = "2021"
authors = ["Erik Bånvik <erik.public@gmail.com>"]
license = "MIT"

[dependencies]
memmap2 = "0.9"
byteorder = "1.4"
libc = "0.2"
log = "0.4"
