[package]
name = "uio-rs-tools"
version = "0.1.0"
edition = "2024"
authors = ["Erik Bånvik <erik.public@gmail.com>"]
license = "MIT"

[dependencies]
clap = "4.0"
env_logger = "0.11"
uio-rs = { version = "0.1", path = "../uio-rs" }
